#!/bin/sh

# Inplace test wrapper for m2vmp2cut. Make install generates for dist versions.

case ${1-} in '') echo; echo m2vmp2cut inplace wrapper:
esac
case $0 in */*) exec ${0%/*}/_build/bin/m2vmp2cut.sh "$@"
        ;; *)   exec _build/bin/m2vmp2cut.sh "$@"
esac
