.TH m2vmp2cut 1 2010-12-13
.SH NAME
m2vmp2cut \- MPEG2 frame accurate cutter
.SH SYNOPSIS
.B m2vmp2cut
.I command
.RI [ argument "... ]"
.SH DESCRIPTION
.B M2vmp2cut
is frame accurate (currently PAL) mpeg2 video (m2v file) with
accompanied mp2 audio (mp2 file) cutter.
Frame accuracy is achieved by re-encoding video around cutpoints.
Audio is cut from separate mp2 file at positions that keep a/v sync as
good as possible (maximum sync difference is around 10-15
milliseconds).
.TP
.B lvev6frames
Old versions of m2vmp2cut supported using lve-generated "edit lists"
for cutpoint information.
With lvev6frames these old edits can be used with this m2vmp2cut
version.
.TP
\fBdemux\fP [\fIfile\fP...]
.B M2vmp2cut
requires mpeg files to be demuxed to elementary streams before
cutting.
This command uses
.BR ProjectX (1)
to do the demuxing.
A separate directory (based on source filename) is created for output
files.
Note that this doubles the disk usage of a particular source file.
.TP
\fBselect\fP \fIdirectory\fP
This command uses new
.B m2vcut-gui
graphical utility for searching cutpoints.
This work is done frame-accurately.
.TP
\fBcut\fP \fIdirectory\fP [\fIoption\fP...]
This command is wrapper to m2vmp2cut.pl (which used to be the frontend
of m2vmp2cut in old versions).
This command has extensive help of it's own.
Note that this (again) adds one third of disk usage so far when this
creates final output file.
.TP
\fBplay\fP \fIdirectory\fP [\fIoption\fP...]
This command runs mplayer for the file created with cut command.
.TP
\fBmove\fP \fIdirectory\fP \fIdestfile\fP
Moves final output file to a new destination.
.TP
\fBgetyuv\fP [\fIdirectory\fP|\fBexamples\fP]
Decodes selected mpeg2 frames as a stream of yuv4mpeg pictures.
Useful for further encoding.
.TP
\fBgetmp2\fP [\fIdirectory\fP|\fBexamples\fP]
Extracts selected mp2 audio data, to be muxed with (re-encoded) video.
Mp2 data can be used as is, or as encoded to mp3 or vorbis.
.TP
.B help
Display help message.
.TP
.B contrib
Contribution material.
Mostly encoding scripts.
The command line interface of the programs these scripts invoke may
change over time \(em there is less quarantees that these work in
future than other
.B m2vmp2cut
functionality, in short term period.
